var text0 = "Studio Nabla is a multi-disciplinary art and design studio founded by Aite Eboigbe in 2017. Here are 10 selected works to give an idea of what we do here. In order to view a work, scroll through the slider to the left, select a work, and scroll horizontally to view. <br> <br> <span style='letter-spacing:2px;'> If you would like to inquire about our services, feel free to contact us at <span><a href='mailto:aite@studionabla.com'>aite@studionabla.com</a></span></span>.";
var text1 = "Capturing his ambiguous style, we designed the wordmark for electronic artist Nohri. Then, we modeled and textured a 3D neon sign, animated wire movement with spline dynamics, and rendered a camera animation. Wordmark designed in Adobe Illustrator. 3D modelling, texturing, and camera animation done in Maxon’s Cinema 4D. <br> <br> 1. The rendered neon sign animation. <br> 2. Nohri's 2019 logo. <br> 3. A screenshot of the pre-render model in Cinema 4D’s viewport.";
var text2 = "We recreated “Piku” from Sectordub's <i>Pikuniku</i> into a 3D model, textured it, and animated an inverse kinematics walk cycle with it in Cinema 4D. <br> <br> 1. The rendered animation of the model and walk cycle. <br> 2. A screenshot of the pre-render model in Cinema 4D’s viewport. <br> 3. The digital artwork for the game featuring Piku.";
var text3 = "We recreated a pair of sunglasses from an unknown brand into a 3D model, textured the frame, and modeled a topographical 3D model with hair materials for the frames. Then, we created an Instagram filter with the frames using Facebook’s Spark AR Studio. We couldn’t export the hair material to Spark AR Studio because it didn’t work nicely with Cinema’s MoGraph toolset so we took the spline from the model and exported an editable object with Cinema’s spline wrap deformer. Unfortunately, Spark AR Studio wasn’t able to handle the large file because of the massive number of polygons in the object so we used a multitude of polygon reduction deformers on the object to reduce the file size. We ended up with a jagged and angular version of the topographical model which only pushed the futuristic design. <br><br> 1. Upclose render of the model in the frame. <br> 2. Full render of the model. <br> 3. Video showing the Instagram filter in use. <br>4. The source material for inspiration of the sunglasses design.";
var text4 = "Working closely with grammy nominated record producer MeLo-X, we scored the show opener for Tidal’s <span><i>Tidal X: 1015</i></span> which featured acts including Beyoncé, Nicki Minaj, and Alicia Keys. We designed a soundscape working with the accompanying visuals to creatively maximize the crowd’s excitement. <br><br> 1. A recording of the show opener from Tidal’s website.<br>2. A screenshot of the opener’s arrangement in Ableton Live 10.";
var text5 = "We are recording audio and scoring the soundtrack to editor and director Celine Clarke's upcoming short film, <span><i>Today</i></span>. Clips are available upon request. Email <span><a href='mailto:aite@studionabla.com'>aite@studionabla.com</a></span> to inquire. <br> <br> 1. Photograph of a scene from the film. <br> 2. Still image of a scene from the film.";
var text6 = "Inspired by .nfo release information files, we developed the website for electronic artist Nohri using ASCII art. We designed it to be have the exact same background color and font as the TextEdit app on MacOS. This alludes to the art work for Nohri’s upcoming project which was also created by Studio Nabla. <br><br>1. Nohri’s website, nohri.net.<br>2. <i>Prequel</i> EP art.";
var text7 = "We designed the logo for NYC start up Heat.wav. Seeing the UI in the app and the heavy use of color inspired us to make a logo that would show color well with its thickness, looked playful yet sharp, and worked well in places with large negative space. <br><br>1. Heat.wav’s 2017 logo. <br>2. A screenshot of Heat.wav’s <span><a target='_blank' href='https://heatwav.co/'>homepage</a></span>.";
var text8 = "We designed the logo for Brooklyn rap collective NXGN CBNT channeling themes of elegance in the serif font type and nonconformity in the unconventional negative spacing. Then we created the artwork for NXGN's single, <i>Night Until Dawn</i>, the first NXGN graphic to use the logo. <br><br>1. NXGN’s 2016 logo.<br>2. <i>Night Until Dawn</i> song art.";
var text9 = "We created the front and back covers for Nohri's debut album, <i>Realms</i> editing a portrait of Nohri shot by Jheyda McGarrell and an illustration created by Legtorn. <br><br>1. <i>Realms</i> Front Artwork <br>2. <i>Realms</i> Back Artwork <br>3. Original portrait image shot by Jheyda McGarrell.<br>4. Original illustration created by Legtorn.";
var text10 = "Worked closely with the alternative recording artist Mia Gladstone to create the cover for her Beats One Radio debut single <i> Revolutionize </i>. <br><br>1. <i> Revolutionize </i> official single art. <br> 2. One of best early versions.";


